"""The interface chat() expects from a UI.

chat() reports everything it does through one ``chat_ui`` object: streamed
tokens, tool spinners, context gauges, verification notices.  Three classes
implement it — ChatUI (the terminal), StreamingAdapter (callback-based
clients such as the web UI and A2A), and nothing (``None``, a run with no
one watching).  This Protocol names the contract so the signature in
chat.py says what it accepts instead of ``Any``, and so a new front end can
be checked against the full surface instead of discovering missing hooks at
runtime.

Two members are deliberately absent: ``notice`` and ``ask_approval``.
chat() probes both with ``getattr`` because they are genuine capabilities,
not guarantees — a UI without ``ask_approval`` simply cannot approve a
gated command, and chat() must refuse rather than crash.  Declaring them
here would promise what half the implementations cannot deliver.

``model_name`` is an attribute, not a method: chat() writes the resolved
model name onto the UI so the interface can label answers with it.
"""

from typing import Protocol, runtime_checkable


@runtime_checkable
class ChatUIProtocol(Protocol):
    """Everything chat() may call on a UI it is handed.

    Implementations: ChatUI (src/ui/text.py), StreamingAdapter
    (src/onit.py).  WebApiUI (src/ui/api.py) never reaches chat() — it
    serves only the onit.py subset (add_message, add_log, tool_log,
    tool_progress, console, launch) — so it does not implement this.
    """

    # ── streaming ────────────────────────────────────────────────────
    def stream_start(self) -> None: ...
    def stream_token(self, token: str) -> None: ...
    def stream_think_token(self, token: str) -> None: ...
    def stream_end(self, elapsed: str = "") -> None: ...
    def stream_fold(self, summary: str = "") -> None: ...

    # ── tool reporting ───────────────────────────────────────────────
    def add_tool_call(self, name: str, arguments: dict) -> None: ...
    def add_tool_result(self, name: str, result: str, truncate: int = 300) -> None: ...
    def show_tool_start(self, name: str, arguments: dict) -> None: ...
    def show_tool_done(self, name: str, result: str, success: bool = True) -> None: ...
    def start_tool_spinner(self, name: str, arguments: dict) -> None: ...
    def stop_tool_spinner(self) -> None: ...
    def start_tool_batch(self, calls: list) -> None: ...
    def end_tool_batch(self) -> None: ...
    def tool_log(self, name: str, data, level: str = "info") -> None: ...
    def tool_progress(self, name: str, elapsed_seconds: int) -> None: ...

    # ── run events ───────────────────────────────────────────────────
    def add_log(self, message: str, level: str = "info") -> None: ...
    def show_context_compaction(self, orig_msg_count: int, summary_chars: int) -> None: ...
    def show_turn_limit(self, limit: int) -> None: ...
    def verification_start(self) -> None: ...
    def verification_end(self, answer: str, note: str) -> None: ...
    def verification_correction(self, answer: str, note: str) -> None: ...

    # ── gauges and accounting ────────────────────────────────────────
    def set_metrics(self, sink: dict) -> None: ...
    def set_token_budgets(self, max_output_tokens: int = 0, max_context_tokens: int = 0) -> None: ...
    def set_context_usage(self, pct: float, max_tokens: int = 0) -> None: ...
    def set_turn_context(self, tools_run: int = 0) -> None: ...

    # ── attributes ───────────────────────────────────────────────────
    model_name: str